pipeline {
    agent any 

    environment {
        IMAGE_NAME = "sheersh123/react-app"
        CONTAINER_NAME = "react-app-container"
        PORT = "3000"
        DOCKERHUB_CREDENTIAL = credentials('dockerhub')
    }

    stages {
        stage('Clone repo') {
            steps {
                git branch: 'main', url: 'https://github.com/Sheersh123/Jenkins.git'
                sh '''
                pwd
                ls -la
                ls -la React-app
                '''
            }
        }

        stage('Build Docker image') {
            steps {
                sh '''
                docker build -t $IMAGE_NAME:latest -f React-app/dockerfile React-app
                '''
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', 
                                                 usernameVariable: 'DOCKER_USER', 
                                                 passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    '''
                }
            }
        }

        stage('Push image to Docker Hub') {
            steps {
                sh 'docker push $IMAGE_NAME:latest'
            }
        }

        stage('Deploy container') {
            steps {
                echo 'Deploying React app container...'
                sh '''
                docker stop $CONTAINER_NAME || true
                docker rm $CONTAINER_NAME || true
                docker pull $IMAGE_NAME:latest
                docker run -d \
                    --name $CONTAINER_NAME \
                    -p 80:$PORT \
                    $IMAGE_NAME:latest
                '''
            }
        }

        stage('Cleanup') {
            steps {
                echo 'Cleaning up Docker resources...'
                sh '''
                docker rmi -f $IMAGE_NAME:latest || true
                docker image prune -f
                docker container prune -f
                '''
            }
        }
    }
}
